import Head from 'next/head'
import Image from 'next/image'
import Navbar from './comps/Navbar';
import Footer from './comps/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Masaki</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/a59b4d3f29.js" crossorigin="anonymous"></script>
      </Head>

      <main className='bg-sky-100 dark:bg-gray-900 min-h-screen'>
        <Navbar />
        <dev className="container">
        <div className="max-w-[1024] mx-auto bg-white bg-opacity-50 rounded-lg p-6 my-6 h-auto">
          <div className="flex justify-center my-[12px]">
                <div className="max-w-[960px] mx-auto bg-white dark:bg-gray-800 rounded-lg p-6">
                    <dev className="text-center mb-4">
                      <h1 className="text-3xl text-blue-400 dark:text-white font-bold">บริการของเรา</h1>
                      <p className="mt-[-3px] text-blue-300 dark:text-gray-400">Our services</p>
                    </dev>
                    <dev className="grid sm:flex justify-center md:grid-cols-3 mb-4">
                      <dev className="p-3 text-center max-w-[300px] text-blue-400">
                        <i class="fa fa-robot text-8xl mb-3"></i>
                          <h1 class="text-2xl font-semibold dark:text-white mb-1 whitespace-nowrap">รับเขียนบอทดิสคอร์ด</h1>
                        <p class="text-sm">รับทำบอทดิสคอร์ด ไม่ว่าจะเป็น บอทเพลง, บอทดูแลความเรียบร้อยใน Discord, บอทแก๊ง, บอทเชื่อมต่อ API</p>
                      </dev>
                      <dev className="p-3 text-center max-w-[300px] text-blue-400">
                        <i class="fa fa-robot text-8xl mb-3"></i>
                          <h1 class="text-2xl font-semibold dark:text-white mb-1 whitespace-nowrap">รับเขียนบอทดิสคอร์ด</h1>
                        <p class="text-sm">รับทำบอทดิสคอร์ด ไม่ว่าจะเป็น บอทเพลง, บอทดูแลความเรียบร้อยใน Discord, บอทแก๊ง, บอทเชื่อมต่อ API</p>
                      </dev>
                      <dev className="p-3 text-center max-w-[300px] text-blue-400">
                        <i class="fa fa-robot text-8xl mb-3"></i>
                          <h1 class="text-2xl font-semibold dark:text-white mb-1 whitespace-nowrap">รับเขียนบอทดิสคอร์ด</h1>
                        <p class="text-sm">รับทำบอทดิสคอร์ด ไม่ว่าจะเป็น บอทเพลง, บอทดูแลความเรียบร้อยใน Discord, บอทแก๊ง, บอทเชื่อมต่อ API</p>
                      </dev>
                    </dev>
                </div>                
          </div>

          <div className="flex justify-center my-[12px]">
                <div className="max-w-[960px] mx-auto bg-white dark:bg-gray-800 rounded-lg p-6">
                    <dev className="text-center mb-4">
                      <h1 className="text-3xl text-blue-400 dark:text-white font-bold">บริการของเรา</h1>
                      <p className="mt-[-3px] text-blue-300 dark:text-gray-400">Our services</p>
                    </dev>
                    <dev className="grid sm:flex justify-center md:grid-cols-3 mb-4">
                      <dev className="p-3 text-center max-w-[300px] text-blue-400">
                        <i class="fa fa-robot text-8xl mb-3"></i>
                          <h1 class="text-2xl font-semibold dark:text-white mb-1 whitespace-nowrap">รับเขียนบอทดิสคอร์ด</h1>
                        <p class="text-sm">รับทำบอทดิสคอร์ด ไม่ว่าจะเป็น บอทเพลง, บอทดูแลความเรียบร้อยใน Discord, บอทแก๊ง, บอทเชื่อมต่อ API</p>
                      </dev>
                      <dev className="p-3 text-center max-w-[300px] text-blue-400">
                        <i class="fa fa-robot text-8xl mb-3"></i>
                          <h1 class="text-2xl font-semibold dark:text-white mb-1 whitespace-nowrap">รับเขียนบอทดิสคอร์ด</h1>
                        <p class="text-sm">รับทำบอทดิสคอร์ด ไม่ว่าจะเป็น บอทเพลง, บอทดูแลความเรียบร้อยใน Discord, บอทแก๊ง, บอทเชื่อมต่อ API</p>
                      </dev>
                      <dev className="p-3 text-center max-w-[300px] text-blue-400">
                        <i class="fa fa-robot text-8xl mb-3"></i>
                          <h1 class="text-2xl font-semibold dark:text-white mb-1 whitespace-nowrap">รับเขียนบอทดิสคอร์ด</h1>
                        <p class="text-sm">รับทำบอทดิสคอร์ด ไม่ว่าจะเป็น บอทเพลง, บอทดูแลความเรียบร้อยใน Discord, บอทแก๊ง, บอทเชื่อมต่อ API</p>
                      </dev>
                    </dev>
                </div>                
          </div>
        </div>
        </dev>
      
            

        <Footer />
      </main>  
    </div>
  );
}
